CREATE TYPE "rule_type" AS ENUM (
  'include',
  'exclude'
);

CREATE TYPE "status_type" AS ENUM (
  'active',
  'inactive'
);

CREATE TABLE "campaign" (
  "cid" text PRIMARY KEY NOT NULL,
  "img" text NOT NULL,
  "cta" text NOT NULL,
  "status" status_type NOT NULL DEFAULT 'active',
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "campaign_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "cid" text NOT NULL,
  "field_changed" text NOT NULL,
  "old_value" text NOT NULL,
  "new_value" text NOT NULL,
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "target_app" (
  "cid" text UNIQUE NOT NULL,
  "app_id" text NOT NULL,
  "rule" rule_type NOT NULL
);

CREATE TABLE "target_os" (
  "cid" text UNIQUE NOT NULL,
  "os" text NOT NULL,
  "rule" rule_type NOT NULL
);

CREATE TABLE "target_country" (
  "cid" text UNIQUE NOT NULL,
  "country" text NOT NULL,
  "rule" rule_type NOT NULL
);

CREATE INDEX ON "campaign" ("status");

CREATE INDEX ON "target_app" ("cid");

CREATE INDEX ON "target_os" ("cid");

CREATE INDEX ON "target_country" ("cid");

CREATE INDEX ON "campaign_history" ("cid");

ALTER TABLE "target_app" ADD FOREIGN KEY ("cid") REFERENCES "campaign" ("cid") ON DELETE CASCADE;

ALTER TABLE "target_os" ADD FOREIGN KEY ("cid") REFERENCES "campaign" ("cid") ON DELETE CASCADE;

ALTER TABLE "target_country" ADD FOREIGN KEY ("cid") REFERENCES "campaign" ("cid") ON DELETE CASCADE;

ALTER TABLE "campaign_history" ADD FOREIGN KEY ("cid") REFERENCES "campaign" ("cid") ON DELETE CASCADE;