// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AddCampaign(ctx context.Context, arg AddCampaignParams) (Campaign, error)
	AddTargetApp(ctx context.Context, arg AddTargetAppParams) (TargetApp, error)
	AddTargetCountry(ctx context.Context, arg AddTargetCountryParams) (TargetCountry, error)
	AddTargetOs(ctx context.Context, arg AddTargetOsParams) (TargetOs, error)
	DeleteCampaign(ctx context.Context, cid string) error
	DeleteTargetApp(ctx context.Context, cid string) error
	DeleteTargetCountry(ctx context.Context, cid string) error
	DeleteTargetOs(ctx context.Context, cid string) error
	GetCampaign(ctx context.Context, cid string) (Campaign, error)
	GetCampaignHistory(ctx context.Context, cid string) (CampaignHistory, error)
	GetLastTwoCampaignHistory(ctx context.Context, cid string) ([]CampaignHistory, error)
	GetTargetApp(ctx context.Context, cid string) (TargetApp, error)
	GetTargetCountry(ctx context.Context, cid string) (TargetCountry, error)
	GetTargetOs(ctx context.Context, cid string) (TargetOs, error)
	ListActiveCampaigns(ctx context.Context) ([]Campaign, error)
	ListCampaignHistory(ctx context.Context, cid string) ([]CampaignHistory, error)
	ListCampaigns(ctx context.Context) ([]Campaign, error)
	createCampaignHistory(ctx context.Context, arg createCampaignHistoryParams) error
	toggleStatus(ctx context.Context, cid string) (StatusType, error)
	updateCampaignCta(ctx context.Context, arg updateCampaignCtaParams) (Campaign, error)
	updateCampaignImage(ctx context.Context, arg updateCampaignImageParams) (Campaign, error)
	updateCampaignName(ctx context.Context, arg updateCampaignNameParams) (Campaign, error)
	updateTargetApp(ctx context.Context, arg updateTargetAppParams) (TargetApp, error)
	updateTargetCountry(ctx context.Context, arg updateTargetCountryParams) (TargetCountry, error)
	updateTargetOs(ctx context.Context, arg updateTargetOsParams) (TargetOs, error)
}

var _ Querier = (*Queries)(nil)
